FROM localhost/linux-oss-toolset-builder:el8-20260923
USER root
RUN dnf -y --enablerepo=powertools --setopt=install_weak_deps=False install \
      readline-devel libselinux-devel pcre2-devel glibc-langpack-en \
    && dnf clean all
USER builder
