FROM localhost/linux-oss-batch-library-builder:el8-20260924-v2
USER root
RUN dnf -y --enablerepo=powertools --setopt=install_weak_deps=False install SDL-devel && dnf clean all
COPY libogg-1.3.6-1.linuxoss.el8.x86_64.rpm libogg-devel-1.3.6-1.linuxoss.el8.x86_64.rpm /tmp/ogg-input/
RUN dnf -y --disablerepo='*' --setopt=localpkg_gpgcheck=False install /tmp/ogg-input/*.rpm
USER builder
