FROM localhost/linux-oss-asn1-validation:el8-20260924
RUN dnf -y --disableplugin=subscription-manager --setopt=install_weak_deps=False \
      install jq oniguruma libXpm libpcap libidn \
    && dnf clean all
