FROM localhost/linux-oss-wave17-builder:el8-20260924
USER root
RUN dnf -y --enablerepo=powertools --setopt=install_weak_deps=False install snappy-devel bind-utils xmlto && dnf clean all
COPY cairo*.rpm fribidi*.rpm pixman*.rpm /tmp/render-deps/
RUN dnf -y --disablerepo='*' --setopt=install_weak_deps=False --setopt=localpkg_gpgcheck=False install /tmp/render-deps/*.rpm
USER builder
