FROM localhost/linux-oss-batch-validation:el8-20260924
RUN dnf -y --disableplugin=subscription-manager --setopt=install_weak_deps=False \
      install file harfbuzz libogg libtiff nano openssh-server openssh-clients openjpeg2 time cairo \
    && dnf clean all
