FROM localhost/linux-oss-wave15-builder:el8-20260924
USER root
RUN dnf -y --enablerepo=powertools --setopt=install_weak_deps=False install protobuf-c-devel libunistring-devel libini_config-devel libcollection-devel libdhash-devel libref_array-devel libpath_utils-devel c-ares-devel libnl3-devel jansson-devel checkpolicy && dnf clean all
COPY *.rpm /tmp/network-deps/
RUN dnf -y --disablerepo='*' --setopt=install_weak_deps=False --setopt=localpkg_gpgcheck=False install /tmp/network-deps/*.rpm
USER builder
